layout.html references theme_root_icon consistently
python/python-docs-theme pull request #163
Opened 2024-01-09 19:05 UTC by mbudisic

Removed explicit `py.svg` references in `layout.html` with `theme_root_icon` paths. 

This pull request changes paths lines 17 and 103 to match line 74 in the base branch.

2024-01-09 19:36 UTC, ezio-melotti approved these changes

2024-01-10 08:31 UTC, hugovk commented
Good idea.

Although "Logo" isn't a great alt text, can we also add something like `root_icon_alt_text` to the config?

* https://webaim.org/techniques/alttext/#logos
* https://sc.edu/about/offices_and_divisions/digital-accessibility/toolbox/best_practices/alternative_text/logo-alt-text/index.php
* https://www.a11yproject.com/posts/alt-text/

2024-01-10 20:47 UTC, hugovk commented on python_docs_theme/theme.conf
> +root_icon_alt_text = Python Logo
```suggestion
root_icon_alt_text = Python logo
```

2024-01-10 21:09 UTC, mbudisic commented on python_docs_theme/theme.conf
> +root_icon_alt_text = Python Logo
Thank you.

2024-01-11 08:51 UTC, hugovk approved these changes
Thanks!

2024-01-11 19:02 UTC, ezio-melotti commented on python_docs_theme/theme.conf
> +root_icon_alt_text = Python logo
Any reason why the two `root_icon*` are not together?
```suggestion
root_icon = py.svg
root_icon_alt_text = Python logo
root_include_title = True
```

2024-01-12 04:38 UTC, AA-Turner requested changes
Per the [documentation](https://jinja.palletsprojects.com/en/3.1.x/templates/#other-operators):

> This, however, is not the preferred way to concatenate strings! For string concatenation, have a look-see at the `~` operator.

https://jinja.palletsprojects.com/en/3.1.x/templates/#other-operators

> Converts all operands into strings and concatenates them.

A

2024-01-12 04:38 UTC, AA-Turner commented on python_docs_theme/layout.html
> +          <li><img src="{{ pathto('_static/' + theme_root_icon, 1) }}" alt="{{theme_root_icon_alt_text}}" style="vertical-align: middle; margin-top: -1px"/></li>
```suggestion
          <li><img src="{{ pathto('_static/' ~ theme_root_icon, 1) }}" alt="{{theme_root_icon_alt_text}}" style="vertical-align: middle; margin-top: -1px"/></li>
```

2024-01-12 04:38 UTC, AA-Turner commented on python_docs_theme/layout.html
> +                <img src="{{ pathto('_static/' + theme_root_icon, 1) }}" alt="{{theme_root_icon_alt_text}}"/>
```suggestion
                <img src="{{ pathto('_static/' ~ theme_root_icon, 1) }}" alt="{{theme_root_icon_alt_text}}"/>
```

2024-01-12 17:44 UTC, merged