create Makefile for faster iteration
python/python-docs-theme pull request #93
Opened 2022-05-02 23:58 UTC by jdevries3133

* makefile can automatically build the package, then navigate to the
  cpython repository to install the package and/or rebuild documentation

2022-05-02 23:59 UTC, jdevries3133 commented
For context, this PR has no associated issue, I created this little Makefile while I was tinkering with this theme, and I thought that it might be useful to others.

2023-01-31 18:57 UTC, hugovk requested changes
Thanks for the PR! A couple of little suggestions.

2023-01-31 18:57 UTC, hugovk commented on Makefile
> +all: install
Could we use the same target names as in the CPython, devguide and PEPs repo? Less confusion and more muscle memory :)

```suggestion
.PHONY: html
html: venv
```

2023-01-31 18:57 UTC, hugovk commented on Makefile
> +install:
```suggestion
.PHONY: venv
venv:
```

2023-01-31 18:57 UTC, hugovk commented on Makefile
> +	@echo "install: 	build the package, and install it into the virtual environment"
```suggestion
	@echo "html:		default rule; run the \`venv\` rule, and also rebuild the CPython docs"
	@echo "venv: 		build the package, and install it into the virtual environment"
```

2023-01-31 18:57 UTC, hugovk commented on CONTRIBUTING.rst
> +# Makefile Usage
Consistency with previous header
```suggestion
# Makefile usage
```

2023-01-31 18:57 UTC, hugovk commented on CONTRIBUTING.rst
> +to the cpython repository on your machine. By default, it points to
```suggestion
the main CPython repository. Run ``make help`` for details on available rules.

There is one configurable variable, ``CPYTHON_PATH``, which should be the path
to the CPython repository on your machine. By default, it points to
```

2023-01-31 19:56 UTC, hugovk commented on Makefile
> +	python3 -m build
And we should install `build` before using.

2023-01-31 20:08 UTC, hugovk commented on Makefile
> +		./venv/bin/pip install $(PACKAGE_ABS_PATH)
And we need a `make venv` in here, as the CPython repo might not have a venv in its `Doc` dir yet (also align ampersands for readability):
```suggestion
	cd $(CPYTHON_PATH)/Doc \
		&& make venv \
		&& ./venv/bin/pip install $(PACKAGE_ABS_PATH)
```

2023-02-06 23:12 UTC, hugovk approved these changes
Thanks!

2023-02-07 16:19 UTC, merged